# Kafka
spring.kafka.bootstrap-servers=localhost:9092
kafka.topics.sensors=telemetry.sensors.v1
kafka.topics.hubs=telemetry.hubs.v1

# Logging
logging.level.ru.yandex.practicum.telemetry.collector=DEBUG
logging.level.org.apache.kafka=WARN