spring.application.name=aggregator

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
kafka.consumer.group-id=aggregator

# Topics
kafka.topics.sensors=telemetry.sensors.v1
kafka.topics.hubs=telemetry.hubs.v1
kafka.topics.snapshots=telemetry.snapshots.v1

# Logging
logging.level.ru.yandex.practicum.aggregator=DEBUG
logging.level.org.apache.kafka=WARN

# Graceful shutdown
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s